POST http://localhost:8000/customers?environment=SANDBOX
Content-Type: application/json
access_token: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmE0MjNhMDc1LTUzYzgtNGMzYi04NTU4LWYyYWEyZmYyMjI4Yjo6JGFhY2hfMDZkNGY5MWItNDBlMS00YjE5LTg1ZjUtMWQxZmQ3YmE1NmI3

{
  "name": "Usuário Teste",
  "cpfCnpj": "571.895.310-41",
  "email": "usuario@teste.com",
  "phone": "+5588992814764",
  "address": "Rua Exemplo",
  "addressNumber": "51",
  "province": "Bairro Exemplo",
  "postalCode": "63100000"
}

###

GET http://localhost:8000/customers?environment=SANDBOX
Content-Type: application/json
access_token: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmE0MjNhMDc1LTUzYzgtNGMzYi04NTU4LWYyYWEyZmYyMjI4Yjo6JGFhY2hfMDZkNGY5MWItNDBlMS00YjE5LTg1ZjUtMWQxZmQ3YmE1NmI3