POST http://localhost:8000/payment-links?environment=SANDBOX
Content-Type: application/json
access_token: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmE0MjNhMDc1LTUzYzgtNGMzYi04NTU4LWYyYWEyZmYyMjI4Yjo6JGFhY2hfMDZkNGY5MWItNDBlMS00YjE5LTg1ZjUtMWQxZmQ3YmE1NmI3

{
  "name": "Jonatas Silva",
  "description": "Comprando um produto de $70.000.000,00 #SQN",
  "value": 100,
  "billingType": "CREDIT_CARD",
  "chargeType": "INSTALLMENT",
  "dueDateLimitDays": 10,
  "maxInstallmentCount": 10
}

###

GET http://localhost:8000/payment-links?environment=SANDBOX
Content-Type: application/json
access_token: $aact_hmlg_000MzkwODA2MWY2OGM3MWRlMDU2NWM3MzJlNzZmNGZhZGY6OmE0MjNhMDc1LTUzYzgtNGMzYi04NTU4LWYyYWEyZmYyMjI4Yjo6JGFhY2hfMDZkNGY5MWItNDBlMS00YjE5LTg1ZjUtMWQxZmQ3YmE1NmI3