version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: asaas_payment_gateway_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: asaas_payment_gateway
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/asaas_payment_gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: asaas_payment_gateway_data 